# Generated by Django 2.2.6 on 2019-10-08 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_cronjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='cronjob',
            name='authentification',
            field=models.BooleanField(default=True),
        ),
    ]
