# Generated by Django 2.2.6 on 2019-10-14 03:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_cronjob_authentification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Friends',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.AlterField(
            model_name='cronjob',
            name='authentification',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cronjob',
            name='user',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
